// Code generated by configtable-gen; DO NOT EDIT.
//
// 批次快照结构与表注册(旧项目 all_table.go 的移植替代):
// 表清单由 proto 描述符驱动(pandora.config.v1 包内打了 (excel_file) 注解的容器,
// 见 excel.proto),加载语义(manifest 驱动 / 全批成功才切换 / 失败保留旧表)统一在 store.go。

package configtable

import (
	"fmt"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// Tables 一个批次的全部配置表快照(原子切换的最小单位,批内跨表版本一致)。
type Tables struct {
	Version   uint64
	SourceRev string

	// Level 配置表 level(关卡/g_关卡.xlsx)
	Level *LevelTable
}

// specByName 清单表名 → 解析构建注册(Store.Load 消费)。
var specByName = map[string]tableSpec{
	"level": {protoName: "pandora.config.v1.LevelTableData", build: buildLevelTable},
}

func buildLevelTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.LevelTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 level 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 level 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newLevelTable(&data)
	if err != nil {
		return err
	}
	dst.Level = t
	return nil
}
