-- Pandora data_service 数据网关表结构(2026-06-16;2026-06-20 移交服务自管)
--
-- ⚠️ 本文件不再建表:player_data 的 schema 唯一来源是
--    proto/pandora/data_service/v1/data_service.proto 的 PlayerData message,
--    data_service 启动时经 proto2mysql CreateOrUpdateTable 按 pb 字段自动
--    建表/同步表结构(表不存在则 CREATE,存在则补缺列/对齐类型,不删多余列)。
--
-- 约定(不变):
--   - data_service 是内网数据网关,MySQL 是事实源,Redis 仅旁路缓存(cache-aside)
--   - 乐观锁:WritePlayer 走 version CAS(UpdateFieldsIfVersion),失配 →
--     ErrDataVersionMismatch(10001);version=0 视为新建走 INSERT
--   - 与 04-player-tables.sql 的 players 表互补:players 归 player 服务,
--     player_data 归 data_service 网关
--   - 改 PlayerData 字段只允许加新编号字段 / reserved 删字段(CLAUDE.md §9 不变量 17)

-- 库由 01-create-databases.sql 创建;此处仅保留占位说明,无 DDL。
