apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - serviceaccounts.yaml

patches:
  - path: inventory.yaml
  - path: auction.yaml
  - path: trade.yaml
  - path: mail.yaml
  - path: leaderboard.yaml
  - path: battle-result.yaml
