apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
  namespace: pandora
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  template:
    metadata:
      labels:
        istio.io/rev: PANDORA_ISTIO_REVISION_REQUIRED
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: pandora-mail
      automountServiceAccountToken: false
      containers:
        - name: mail
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: ["ALL"]
