apiVersion: v1
kind: ServiceAccount
metadata:
  name: pandora-inventory
  namespace: pandora
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pandora-auction
  namespace: pandora
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pandora-trade
  namespace: pandora
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pandora-mail
  namespace: pandora
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pandora-leaderboard
  namespace: pandora
automountServiceAccountToken: false
