package gogen

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/luyuancpp/pandora/tools/configtable-gen/internal/tablegen"
)

func discover(t *testing.T) []tablegen.TableDef {
	t.Helper()
	defs, err := tablegen.Discover()
	if err != nil {
		t.Fatalf("Discover: %v", err)
	}
	return defs
}

func TestFilesShape(t *testing.T) {
	files, err := Files(discover(t))
	if err != nil {
		t.Fatalf("Files: %v", err)
	}
	tbl, ok := files["level_table.gen.go"]
	if !ok {
		t.Fatalf("缺 level_table.gen.go,产物: %v", keys(files))
	}
	for _, want := range []string{
		"// Code generated by configtable-gen; DO NOT EDIT.",
		"源表:关卡/g_关卡.xlsx",
		"type LevelTable struct",
		"func newLevelTable(data *configpb.LevelTableData)",
		"validateLevelRow(row)", // 依赖手写伴生钩子
		"func (t *LevelTable) ByID(key uint32)",
		"func (t *LevelTable) ByIDs(keys []uint32)",
		"func (t *LevelTable) RandOne()",
		"func (t *LevelTable) Where(",
		"func (t *LevelTable) First(",
	} {
		if !strings.Contains(string(tbl), want) {
			t.Errorf("level_table.gen.go 缺少 %q", want)
		}
	}
	reg, ok := files["tables.gen.go"]
	if !ok {
		t.Fatal("缺 tables.gen.go")
	}
	for _, want := range []string{
		"type Tables struct",
		"Level *LevelTable",
		`"level": {protoName: "pandora.config.v1.LevelTableData", build: buildLevelTable}`,
		"func buildLevelTable(raw []byte, mt ManifestTable, dst *Tables) error",
	} {
		if !strings.Contains(string(reg), want) {
			t.Errorf("tables.gen.go 缺少 %q", want)
		}
	}
}

func TestCompanionStubShape(t *testing.T) {
	defs := discover(t)
	stub, err := CompanionStub(defs[0])
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(stub), "func validateLevelRow(row *configpb.LevelRow) error") {
		t.Fatalf("伴生桩缺钩子: %s", stub)
	}
	if strings.Contains(string(stub), "DO NOT EDIT") {
		t.Fatal("伴生桩归人维护,不应带 DO NOT EDIT 头")
	}
}

// TestGeneratedFilesUpToDate 守护「生成代码与 proto 注解同步」:
// 改了 excel 注解 / 模板却没重跑生成器,或有人手改了 *.gen.go,这里失败。
func TestGeneratedFilesUpToDate(t *testing.T) {
	pkgDir := filepath.Join("..", "..", "..", "..", "pkg", "configtable")
	if _, err := os.Stat(pkgDir); err != nil {
		t.Skipf("pkg/configtable 不存在,跳过: %v", err)
	}
	files, err := Files(discover(t))
	if err != nil {
		t.Fatal(err)
	}
	for name, want := range files {
		got, err := os.ReadFile(filepath.Join(pkgDir, name))
		if err != nil {
			t.Errorf("读 %s 失败(新表生成后未落盘?): %v", name, err)
			continue
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s 与 proto 注解不同步,请重跑: go run ./tools/configtable-gen -tables <Table根目录>", name)
		}
	}
	// 每张表的伴生文件必须存在(桩由生成器首跑创建,之后归人维护)
	for _, def := range discover(t) {
		if _, err := os.Stat(filepath.Join(pkgDir, def.Name+".go")); err != nil {
			t.Errorf("缺伴生文件 %s.go: %v", def.Name, err)
		}
	}
}

// TestFilesDeterministic 生成产物字节级确定(重复跑无 git 噪音)。
func TestFilesDeterministic(t *testing.T) {
	defs := discover(t)
	a, err := Files(defs)
	if err != nil {
		t.Fatal(err)
	}
	b, err := Files(defs)
	if err != nil {
		t.Fatal(err)
	}
	for name := range a {
		if !bytes.Equal(a[name], b[name]) {
			t.Errorf("%s 生成不确定", name)
		}
	}
}

func keys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
